### PR TITLE
Add "About our License Process" section to LicenseAgreementView

### PR DESCRIPTION
**Pull request by DavidBoike**
Connects to https://github.com/Particular/OptimizeTrialExtensions/issues/10, see specifically https://github.com/Particular/OptimizeTrialExtensions/issues/10#issuecomment-255761710

Be gentle with me, this is my very first foray of any kind into WPF or XAML.

With the change, the license agreement dialog looks like this:

image

Please review @Particular/serviceinsight-maintainers, cc @adamralph

### CODE REVIEW

**Comment by gbiellem** [comment]
@DavidBoike  I think you mean @Particular/platforminstaller-maintainers  :)

**Comment by SimonCropp** [comment]
remove the screaming caps in "FREE" make it bold if u want it emphasise it.

Also please add a link to that text to where the trial process is explained

**Comment by gbiellem** [comment]
> Also please add a link to that text to where the trial process is explained

I don't think there is a link currently that @DavidBoike could link to yet.  There does seem to be an issue for creating one -> https://github.com/Particular/OptimizeTrialExtensions/issues/126

**Comment by adamralph** [comment]
> remove the screaming caps in "FREE" make it bold if u want it emphasise it.

If we do this, we should change the dialog in NSB similarly - https://github.com/Particular/NServiceBus/pull/4146#issuecomment-249235425

I'm not too bothered whether it's bold or caps. Perhaps @sergioc has an opinion?

**Comment by sergioc** [comment]
> About License process

This title suggests much more than just the trial-centric copy in "Your initial trial lasts for 14 days, but after that you instantly extend it for FREE."

**Comment by adamralph** [comment]
@sergioc good point. Maybe we should remove that subheading completely?

**Comment by sergioc** [comment]
I'd make these changes:

> **About licenses and trialing**

> Unless you have purchased a license, all Particular Software can be evaluated for free during 14 days. 
>
> When the trial is over, you will be offered the option to instantly receive an extended trial license and use it for another 30 days, for free.

**Comment by DavidBoike** [comment]
@sergioc: The word **trialing**, while probably technically correct, sounds like too weird of a word to actually use. And that is a lot more words. The idea at the outset was to keep it simple (not exhaustive, after all it's right next to the EULA) and to not put a numeric ceiling on it. If you spell it out too much they'll do 14 + 30 and they'll decide that's not enough and then they're gone.

What if the heading was just changed to "About the Evaluation Period" or, as @adamralph suggested, removed altogether?

The FREE I think we can make lowercase and bold, although having styled text within a label (or links, for that matter) is more complex than when the label is all one format.

**Comment by gbiellem** [comment]
:+1: for removing the heading, I think it's redundant

**Comment by sergioc** [comment]
I think all caps FREE is fine. How about just

> Unless you have purchased a license, your initial trial lasts for 14 days. When the trial expires you can instantly extend it for FREE.

or

> Unless you have purchased a license, your initial trial lasts for 14 days. When the trial expires you can register to instantly extend it for FREE.

I prefer the 2nd because the first will easily leave questions open.

**Comment by adamralph** [comment]
> Unless you have purchased a license...

Good call @sergioc - we're assuming the user hasn't already purchased a license, which they may have. We should add this.

I think I prefer the first:

> Unless you have purchased a license, your initial trial lasts for 14 days. When the trial expires you can instantly extend it for FREE.

It flows better than having "register to" in there as well.

@sergioc what question do you think this sentence would leave open?

**Comment by sergioc** [comment]
> @sergioc what question do you think this sentence would leave open?

"How come I have to wait until then to extend for free? How can I extend it for free then?"

**Comment by gbiellem** [comment]
We could look for a license and suppress the dialog  completely for licensed users.

**Comment by adamralph** [comment]
> We could look for a license and suppress the dialog completely for licensed users.

@gbiellem 👍 no need to show this at all in that case. Come to think of it, is this not already the case?

**Comment by adamralph** [comment]
@sergioc 

> How come I have to wait until then to extend for free?

I doubt this question will come up. I don't see the motivation to extend or interesting in extending the trial before I have to.

> How can I extend it for free then?

👍 it may be worth including something about this. Perhaps:

> Unless you have purchased a license, your initial trial lasts for 14 days. When the trial expires we'll provide instructions for how to extend it for FREE.

(Initial idea, language needs work.)

**Comment by gbiellem** [comment]
> Come to think of it, is this not already the case?

No - at the moment PI has no licensing code in it. I'd be happy to add this to this PR or do it separately. I'll let you guys make that call

I believe the current code only checks a reg key to see if the dialog has ever been shown before and suppresses it if it has.

**Comment by adamralph** [comment]
Thanks for the explanation @gbiellem - makes sense.

@DavidBoike what do you think? I'm leaning toward keeping this PR simple and only changing the text. I think the license check would be good but it can be done independently. It would make "Unless you have purchased a license..." redundant so that text could be removed when that change is made.

**Comment by DavidBoike** [comment]
It does indeed check a reg key to see if the dialog has ever been shown before. So it's only going to show the first time you execute it on any given machine, and we say not to use it in Prod, so hopefully just your dev machine. So likely they will **not** already have a license. (If they did, it would be because they're setting up a new machine, they're already a customer, and they're just going to blow through this dialog so we don't really care.)

So I think the "Unless" language is irrelevant and shouldn't be included, plus we should take out the header. If you take that out of @sergioc's earlier comment, we're left with a small variation on what we had originally:

> Your initial trial lasts for 14 days. When the trial expires we'll provide instructions on how to extend it for {FREE|**free**}.

vs. the original

> Your initial trial lasts for 14 days, but after that you can instantly extend it for {FREE|**free**}.

I think we should focus around coming to agreement on the small variation here. I think I prefer the former because the "provide instructions" bit does add a small amount of value in answering the question "how?"

**Comment by sergioc** [comment]
Is the reg key check really necessary? If the user already installed, then I doubt seeing that message again will convince to *not* install again... if the user will blow through the screens, why bother disabling the text?

How about a new employee from a customer that already has a license, but never installed before?

**Comment by DavidBoike** [comment]
The reg key check is *already there*, before this PR, because we only need to show people the EULA once.

I really think that's out of scope for *this* PR. Let's focus on the words.

**Comment by DavidBoike** [comment]
Removed the first heading, edited the text, and replaced FREE with **free**.

Rebased and updated the new screenshot in the issue description.

**Comment by gbiellem** [comment]
@DavidBoike looks like you're done here.  Shall I merge and release it?

**Comment by DavidBoike** [comment]
@gbiellem Yep I'm :+1:

**Comment by adamralph** [comment]
@Particular/optimize-trial-extensions-squad please note that it is likely that installer is going to be released imminently with these changes. Please take this into account when measuring OTC metrics.

**Comment by gbiellem** [comment]
This change is now live

**Comment by adamralph** [comment]
Thanks @gbiellem !

**Pull request merged**
