### PR TITLE
Rework PI to address #181 and cleanup

### PR DESCRIPTION
**Pull request by gbiellem**
Related to #181

### CODE REVIEW

**Comment by gbiellem** [comment]
@SimonCropp  probably time for you to take a look at this

**Comment by gbiellem** [comment]
At this stage I've smoke tested the changes to the installers on Win 7 and Win 10 only.  I'll check it on other OSes and report back

**Comment by gbiellem** [comment]
Smoke tested on Win2008R2 and 16 bit versions of Win10 and WIn7.  No issues with the DISM changes.
The feedback when installing the non MSI components needs some work.  @SimonCropp do you think we actually need the dos style feedback  window any more? 
I think originally we introduced it because of the chocolatey integration in the earlier versions.

**Comment by SimonCropp** [comment]
> do you think we actually need the dos style feedback window any more? I think originally we introduced it because of the chocolatey integration in the earlier versions.

happy to kill it

**Comment by gbiellem** [comment]
@SimonCropp Can you give this a review. I'd like to finalize it

**Pull request merged**
